# Generated by Django 3.2.6 on 2021-09-08 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, default=None, max_length=100)),
                ('ram', models.IntegerField(blank=True, null=True)),
                ('rom', models.IntegerField(blank=True, null=True)),
                ('expandable', models.IntegerField(blank=True, null=True)),
                ('display', models.FloatField(blank=True, null=True)),
                ('camera', models.CharField(blank=True, max_length=100)),
                ('battery', models.IntegerField(blank=True, null=True)),
                ('processor', models.CharField(blank=True, max_length=100)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('warranty', models.CharField(blank=True, max_length=200)),
                ('star', models.IntegerField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('review', models.IntegerField(blank=True, null=True)),
                ('in_the_box', models.CharField(blank=True, max_length=200)),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mobiles.product_type')),
            ],
        ),
    ]
