# Generated by Django 3.2.6 on 2021-09-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='star',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
