# Generated by Django 3.2.6 on 2021-09-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0002_alter_product_details_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='battery',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
