# Generated by Django 3.2.6 on 2021-09-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0003_alter_product_details_battery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_details',
            old_name='rating',
            new_name='internal_storage',
        ),
        migrations.RemoveField(
            model_name='product_details',
            name='rom',
        ),
        migrations.AddField(
            model_name='product_details',
            name='rating_review',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='display',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
