# Generated by Django 3.2.6 on 2021-09-14 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0004_auto_20210914_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_details',
            name='review',
        ),
    ]
